### ISSUE TITLE
引入第三方npm包后打包运行，提示不支持class关键字

### ISSUE THREAD

**Issue by Pandaver** [wanZzz6/autoX-webpack-template#1]
src/index.js
```
const RequestQueryBuilder = require('@dataui/crud-request')

const queryString = RequestQueryBuilder.create({
  fields: ['name', 'email'],
  search: { isActive: true },
  join: [{ field: 'company' }],
  sort: [{ field: 'id', order: 'DESC' }],
  page: 1,
  limit: 25,
  resetCache: true,
}).query();

console.log(queryString);
```

输出
```
11:12:17.742/V: 开始运行[[remote]app.js]
11:12:17.750/E: SyntaxError: identifier is a reserved word: class ([remote]app.js#109(eval)#4)
SyntaxError: identifier is a reserved word: class
    at [remote]app.js:109:0
    at __webpack_require__ ([remote]app.js:20:0)
    at [remote]app.js#97(eval):17:0
    at [remote]app.js:97:0
    at __webpack_require__ ([remote]app.js:20:0)
    at [remote]app.js#121(eval):17:0
    at [remote]app.js:121:0
    at __webpack_require__ ([remote]app.js:20:0)
    at [remote]app.js#539(eval):3:0
    at [remote]app.js:539:0
    at __webpack_require__ ([remote]app.js:20:0)
    at [remote]app.js:84:0
    at [remote]app.js:1:0

11:12:17.751/V: 
 ------------ 
 [ [remote]app.js ]运行结束，用时0.008000秒
```

在disk/app.js中能搜索到class定义，怎么才能把所有class转为function的方式？
使用[kkevsekk1/webpack-autojs](https://github.com/kkevsekk1/webpack-autojs)打包也会出现这个问题，但把打包后的代码再打包一次就好使了，class就都消失了
不知道怎么改webpack配置能实现

**Comment by wanZzz6** [comment]
稍微修改了下webpack 配置，你试试可以了吗
![image](https://github.com/wanZzz6/autoX-webpack-template/assets/28629837/15beb2ae-eb94-439e-94ce-fcb27a037d6c)

**Comment by Pandaver** [comment]
好使，非常感谢
package.json少了javascript-obfuscator记得加一下
![截图_20231022210943](https://github.com/wanZzz6/autoX-webpack-template/assets/62326552/7b5a7123-8f43-4ff6-9093-ca37b65f3749)
